---
- name: my test playook
  hosts: all
  become: true
  tasks:
   - name: copy a file
     copy:
      src: /home/ansadmin/index.html
      dest: /home/ansadmin
      mode: 0600
      owner: akash

