---
- name: my test playbook
  hosts: webserver
  become: true
  tasks:
  - name: install httpd package
    yum:
     name: httpd
     state: latest
  
  - name: start httpd service
    service: 
     name: httpd
     state: started    
