---
- name: my test playbook
  hosts: all
  become: true
  tasks:
  - name: to installing multiple packages
    yum:
     name: ['git', 'make', 'gcc', 'wget', 'tree', 'which', 'docker']
     state: latest   
